/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Zaun) {
      root.Zaun = {};
    }
    root.Zaun.AnalyticApi = factory(root.Zaun.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Analytic service.
   * @module api/AnalyticApi
   * @version 1.0.0
   */

  /**
   * Constructs a new AnalyticApi. 
   * @alias module:api/AnalyticApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the analyticsBotIdDeploymentIdObjectGet operation.
     * @callback module:api/AnalyticApi~analyticsBotIdDeploymentIdObjectGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Object>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get analytic data
     * @param {String} botId Bot ID
     * @param {String} deploymentId Deployment ID
     * @param {module:model/String} _object Object
     * @param {Object} opts Optional parameters
     * @param {String} opts.args Additional arguments such as channelId, startTimestamp, endTimestamp, etc
     * @param {module:api/AnalyticApi~analyticsBotIdDeploymentIdObjectGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Object>}
     */
    this.analyticsBotIdDeploymentIdObjectGet = function(botId, deploymentId, _object, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling analyticsBotIdDeploymentIdObjectGet");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling analyticsBotIdDeploymentIdObjectGet");
      }

      // verify the required parameter '_object' is set
      if (_object == undefined || _object == null) {
        throw new Error("Missing the required parameter '_object' when calling analyticsBotIdDeploymentIdObjectGet");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId,
        'object': _object
      };
      var queryParams = {
        'args': opts['args']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Object];

      return this.apiClient.callApi(
        '/analytics/{botId}/{deploymentId}/{object}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
