/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Channel', 'model/InlineResponse2002'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Channel'), require('../model/InlineResponse2002'));
  } else {
    // Browser globals (root is window)
    if (!root.Zaun) {
      root.Zaun = {};
    }
    root.Zaun.ChannelApi = factory(root.Zaun.ApiClient, root.Zaun.Channel, root.Zaun.InlineResponse2002);
  }
}(this, function(ApiClient, Channel, InlineResponse2002) {
  'use strict';

  /**
   * Channel service.
   * @module api/ChannelApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ChannelApi. 
   * @alias module:api/ChannelApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDepIdChannelsChannelIdDelete operation.
     * @callback module:api/ChannelApi~botsBotIdDeploymentsDepIdChannelsChannelIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete channel by ID
     * @param {String} botId ID of bot
     * @param {String} depId ID of deployment to update
     * @param {String} channelId ID of channel to delete
     * @param {module:api/ChannelApi~botsBotIdDeploymentsDepIdChannelsChannelIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    this.botsBotIdDeploymentsDepIdChannelsChannelIdDelete = function(botId, depId, channelId, callback) {
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDepIdChannelsChannelIdDelete");
      }

      // verify the required parameter 'depId' is set
      if (depId == undefined || depId == null) {
        throw new Error("Missing the required parameter 'depId' when calling botsBotIdDeploymentsDepIdChannelsChannelIdDelete");
      }

      // verify the required parameter 'channelId' is set
      if (channelId == undefined || channelId == null) {
        throw new Error("Missing the required parameter 'channelId' when calling botsBotIdDeploymentsDepIdChannelsChannelIdDelete");
      }


      var pathParams = {
        'botId': botId,
        'depId': depId,
        'channelId': channelId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Channel;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{depId}/channels/{channelId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDepIdChannelsChannelIdGet operation.
     * @callback module:api/ChannelApi~botsBotIdDeploymentsDepIdChannelsChannelIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find channel by ID
     * @param {String} botId ID of bot
     * @param {String} depId ID of deployment to update
     * @param {String} channelId ID of channel
     * @param {module:api/ChannelApi~botsBotIdDeploymentsDepIdChannelsChannelIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    this.botsBotIdDeploymentsDepIdChannelsChannelIdGet = function(botId, depId, channelId, callback) {
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDepIdChannelsChannelIdGet");
      }

      // verify the required parameter 'depId' is set
      if (depId == undefined || depId == null) {
        throw new Error("Missing the required parameter 'depId' when calling botsBotIdDeploymentsDepIdChannelsChannelIdGet");
      }

      // verify the required parameter 'channelId' is set
      if (channelId == undefined || channelId == null) {
        throw new Error("Missing the required parameter 'channelId' when calling botsBotIdDeploymentsDepIdChannelsChannelIdGet");
      }


      var pathParams = {
        'botId': botId,
        'depId': depId,
        'channelId': channelId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Channel;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{depId}/channels/{channelId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDepIdChannelsChannelIdPut operation.
     * @callback module:api/ChannelApi~botsBotIdDeploymentsDepIdChannelsChannelIdPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update channel by ID
     * @param {String} botId ID of bot
     * @param {String} depId ID of deployment to update
     * @param {String} channelId ID of channel to update
     * @param {module:model/Channel} body Channel object
     * @param {module:api/ChannelApi~botsBotIdDeploymentsDepIdChannelsChannelIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    this.botsBotIdDeploymentsDepIdChannelsChannelIdPut = function(botId, depId, channelId, body, callback) {
      var postBody = body;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDepIdChannelsChannelIdPut");
      }

      // verify the required parameter 'depId' is set
      if (depId == undefined || depId == null) {
        throw new Error("Missing the required parameter 'depId' when calling botsBotIdDeploymentsDepIdChannelsChannelIdPut");
      }

      // verify the required parameter 'channelId' is set
      if (channelId == undefined || channelId == null) {
        throw new Error("Missing the required parameter 'channelId' when calling botsBotIdDeploymentsDepIdChannelsChannelIdPut");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling botsBotIdDeploymentsDepIdChannelsChannelIdPut");
      }


      var pathParams = {
        'botId': botId,
        'depId': depId,
        'channelId': channelId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Channel;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{depId}/channels/{channelId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDepIdChannelsGet operation.
     * @callback module:api/ChannelApi~botsBotIdDeploymentsDepIdChannelsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all channels
     * @param {String} botId ID of bot
     * @param {String} depId ID of deployment to update
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Limit returned channels in a page
     * @param {Number} opts.page A number representing page
     * @param {module:api/ChannelApi~botsBotIdDeploymentsDepIdChannelsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2002}
     */
    this.botsBotIdDeploymentsDepIdChannelsGet = function(botId, depId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDepIdChannelsGet");
      }

      // verify the required parameter 'depId' is set
      if (depId == undefined || depId == null) {
        throw new Error("Missing the required parameter 'depId' when calling botsBotIdDeploymentsDepIdChannelsGet");
      }


      var pathParams = {
        'botId': botId,
        'depId': depId
      };
      var queryParams = {
        'limit': opts['limit'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2002;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{depId}/channels', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDepIdChannelsPost operation.
     * @callback module:api/ChannelApi~botsBotIdDeploymentsDepIdChannelsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a channel
     * @param {module:model/Channel} body Channel object
     * @param {String} botId ID of bot
     * @param {String} depId ID of deployment
     * @param {module:api/ChannelApi~botsBotIdDeploymentsDepIdChannelsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    this.botsBotIdDeploymentsDepIdChannelsPost = function(body, botId, depId, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling botsBotIdDeploymentsDepIdChannelsPost");
      }

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDepIdChannelsPost");
      }

      // verify the required parameter 'depId' is set
      if (depId == undefined || depId == null) {
        throw new Error("Missing the required parameter 'depId' when calling botsBotIdDeploymentsDepIdChannelsPost");
      }


      var pathParams = {
        'botId': botId,
        'depId': depId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Channel;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{depId}/channels', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
