/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Channel', 'model/InlineResponse2002'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Channel'), require('../model/InlineResponse2002'));
  } else {
    // Browser globals (root is window)
    if (!root.Zaun) {
      root.Zaun = {};
    }
    root.Zaun.ChannelApi = factory(root.Zaun.ApiClient, root.Zaun.Channel, root.Zaun.InlineResponse2002);
  }
}(this, function(ApiClient, Channel, InlineResponse2002) {
  'use strict';

  /**
   * Channel service.
   * @module api/ChannelApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ChannelApi. 
   * @alias module:api/ChannelApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdChannelsChannelIdDelete operation.
     * @callback module:api/ChannelApi~botsBotIdDeploymentsDeploymentIdChannelsChannelIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete channel by ID
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment to update
     * @param {String} channelId ID of channel to delete
     * @param {module:api/ChannelApi~botsBotIdDeploymentsDeploymentIdChannelsChannelIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    this.botsBotIdDeploymentsDeploymentIdChannelsChannelIdDelete = function(botId, deploymentId, channelId, callback) {
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdChannelsChannelIdDelete");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdChannelsChannelIdDelete");
      }

      // verify the required parameter 'channelId' is set
      if (channelId == undefined || channelId == null) {
        throw new Error("Missing the required parameter 'channelId' when calling botsBotIdDeploymentsDeploymentIdChannelsChannelIdDelete");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId,
        'channelId': channelId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Channel;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}/channels/{channelId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdChannelsChannelIdGet operation.
     * @callback module:api/ChannelApi~botsBotIdDeploymentsDeploymentIdChannelsChannelIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find channel by ID
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment to update
     * @param {String} channelId ID of channel
     * @param {module:api/ChannelApi~botsBotIdDeploymentsDeploymentIdChannelsChannelIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    this.botsBotIdDeploymentsDeploymentIdChannelsChannelIdGet = function(botId, deploymentId, channelId, callback) {
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdChannelsChannelIdGet");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdChannelsChannelIdGet");
      }

      // verify the required parameter 'channelId' is set
      if (channelId == undefined || channelId == null) {
        throw new Error("Missing the required parameter 'channelId' when calling botsBotIdDeploymentsDeploymentIdChannelsChannelIdGet");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId,
        'channelId': channelId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Channel;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}/channels/{channelId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdChannelsChannelIdPut operation.
     * @callback module:api/ChannelApi~botsBotIdDeploymentsDeploymentIdChannelsChannelIdPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update channel by ID
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment to update
     * @param {String} channelId ID of channel to update
     * @param {module:model/Channel} body Channel object
     * @param {module:api/ChannelApi~botsBotIdDeploymentsDeploymentIdChannelsChannelIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    this.botsBotIdDeploymentsDeploymentIdChannelsChannelIdPut = function(botId, deploymentId, channelId, body, callback) {
      var postBody = body;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdChannelsChannelIdPut");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdChannelsChannelIdPut");
      }

      // verify the required parameter 'channelId' is set
      if (channelId == undefined || channelId == null) {
        throw new Error("Missing the required parameter 'channelId' when calling botsBotIdDeploymentsDeploymentIdChannelsChannelIdPut");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling botsBotIdDeploymentsDeploymentIdChannelsChannelIdPut");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId,
        'channelId': channelId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Channel;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}/channels/{channelId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdChannelsGet operation.
     * @callback module:api/ChannelApi~botsBotIdDeploymentsDeploymentIdChannelsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all channels
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment to update
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Limit returned channels in a page
     * @param {Number} opts.page A number representing page
     * @param {module:api/ChannelApi~botsBotIdDeploymentsDeploymentIdChannelsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2002}
     */
    this.botsBotIdDeploymentsDeploymentIdChannelsGet = function(botId, deploymentId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdChannelsGet");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdChannelsGet");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId
      };
      var queryParams = {
        'limit': opts['limit'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2002;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}/channels', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdChannelsPost operation.
     * @callback module:api/ChannelApi~botsBotIdDeploymentsDeploymentIdChannelsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a channel
     * @param {module:model/Channel} body Channel object
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment
     * @param {module:api/ChannelApi~botsBotIdDeploymentsDeploymentIdChannelsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    this.botsBotIdDeploymentsDeploymentIdChannelsPost = function(body, botId, deploymentId, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling botsBotIdDeploymentsDeploymentIdChannelsPost");
      }

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdChannelsPost");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdChannelsPost");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Channel;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}/channels', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
