/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Deployment', 'model/InlineResponse2001'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Deployment'), require('../model/InlineResponse2001'));
  } else {
    // Browser globals (root is window)
    if (!root.Zaun) {
      root.Zaun = {};
    }
    root.Zaun.DeploymentApi = factory(root.Zaun.ApiClient, root.Zaun.Deployment, root.Zaun.InlineResponse2001);
  }
}(this, function(ApiClient, Deployment, InlineResponse2001) {
  'use strict';

  /**
   * Deployment service.
   * @module api/DeploymentApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DeploymentApi. 
   * @alias module:api/DeploymentApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdDelete operation.
     * @callback module:api/DeploymentApi~botsBotIdDeploymentsDeploymentIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Deployment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete deployment by ID
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment to delete
     * @param {module:api/DeploymentApi~botsBotIdDeploymentsDeploymentIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Deployment}
     */
    this.botsBotIdDeploymentsDeploymentIdDelete = function(botId, deploymentId, callback) {
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdDelete");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdDelete");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Deployment;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdGet operation.
     * @callback module:api/DeploymentApi~botsBotIdDeploymentsDeploymentIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Deployment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find deployment by ID
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment to return
     * @param {module:api/DeploymentApi~botsBotIdDeploymentsDeploymentIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Deployment}
     */
    this.botsBotIdDeploymentsDeploymentIdGet = function(botId, deploymentId, callback) {
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdGet");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdGet");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Deployment;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdPut operation.
     * @callback module:api/DeploymentApi~botsBotIdDeploymentsDeploymentIdPutCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update deployment by ID
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment to update
     * @param {module:model/Deployment} body Deployment
     * @param {module:api/DeploymentApi~botsBotIdDeploymentsDeploymentIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    this.botsBotIdDeploymentsDeploymentIdPut = function(botId, deploymentId, body, callback) {
      var postBody = body;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdPut");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdPut");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling botsBotIdDeploymentsDeploymentIdPut");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Object;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsGet operation.
     * @callback module:api/DeploymentApi~botsBotIdDeploymentsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all bot deployments
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Limit returned bots in a page
     * @param {Number} opts.page A number representing page
     * @param {module:api/DeploymentApi~botsBotIdDeploymentsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2001}
     */
    this.botsBotIdDeploymentsGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'limit': opts['limit'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsPost operation.
     * @callback module:api/DeploymentApi~botsBotIdDeploymentsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Deployment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create bot deployment
     * @param {String} botId ID of bot to deploy
     * @param {Object} opts Optional parameters
     * @param {module:model/Deployment} opts.body Deployment object
     * @param {module:api/DeploymentApi~botsBotIdDeploymentsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Deployment}
     */
    this.botsBotIdDeploymentsPost = function(botId, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsPost");
      }


      var pathParams = {
        'botId': botId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Deployment;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
