/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2003', 'model/Schedule'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse2003'), require('../model/Schedule'));
  } else {
    // Browser globals (root is window)
    if (!root.Zaun) {
      root.Zaun = {};
    }
    root.Zaun.ScheduleApi = factory(root.Zaun.ApiClient, root.Zaun.InlineResponse2003, root.Zaun.Schedule);
  }
}(this, function(ApiClient, InlineResponse2003, Schedule) {
  'use strict';

  /**
   * Schedule service.
   * @module api/ScheduleApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ScheduleApi. 
   * @alias module:api/ScheduleApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdSchedulesGet operation.
     * @callback module:api/ScheduleApi~botsBotIdDeploymentsDeploymentIdSchedulesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all schedules
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment to update
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Limit returned schedules in a page
     * @param {Number} opts.page A number representing page
     * @param {module:api/ScheduleApi~botsBotIdDeploymentsDeploymentIdSchedulesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    this.botsBotIdDeploymentsDeploymentIdSchedulesGet = function(botId, deploymentId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdSchedulesGet");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdSchedulesGet");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId
      };
      var queryParams = {
        'limit': opts['limit'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}/schedules', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdSchedulesPost operation.
     * @callback module:api/ScheduleApi~botsBotIdDeploymentsDeploymentIdSchedulesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Schedule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a schedule
     * @param {module:model/Schedule} body Schedule object
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment
     * @param {module:api/ScheduleApi~botsBotIdDeploymentsDeploymentIdSchedulesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Schedule}
     */
    this.botsBotIdDeploymentsDeploymentIdSchedulesPost = function(body, botId, deploymentId, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling botsBotIdDeploymentsDeploymentIdSchedulesPost");
      }

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdSchedulesPost");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdSchedulesPost");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Schedule;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}/schedules', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdDelete operation.
     * @callback module:api/ScheduleApi~botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Schedule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete schedule by ID
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment to update
     * @param {String} scheduleId ID of schedule to delete
     * @param {module:api/ScheduleApi~botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Schedule}
     */
    this.botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdDelete = function(botId, deploymentId, scheduleId, callback) {
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdDelete");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdDelete");
      }

      // verify the required parameter 'scheduleId' is set
      if (scheduleId == undefined || scheduleId == null) {
        throw new Error("Missing the required parameter 'scheduleId' when calling botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdDelete");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId,
        'scheduleId': scheduleId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Schedule;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}/schedules/{scheduleId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdGet operation.
     * @callback module:api/ScheduleApi~botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Schedule} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find schedule by ID
     * @param {String} botId ID of bot
     * @param {String} deploymentId ID of deployment to update
     * @param {String} scheduleId ID of schedule
     * @param {module:api/ScheduleApi~botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Schedule}
     */
    this.botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdGet = function(botId, deploymentId, scheduleId, callback) {
      var postBody = null;

      // verify the required parameter 'botId' is set
      if (botId == undefined || botId == null) {
        throw new Error("Missing the required parameter 'botId' when calling botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdGet");
      }

      // verify the required parameter 'deploymentId' is set
      if (deploymentId == undefined || deploymentId == null) {
        throw new Error("Missing the required parameter 'deploymentId' when calling botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdGet");
      }

      // verify the required parameter 'scheduleId' is set
      if (scheduleId == undefined || scheduleId == null) {
        throw new Error("Missing the required parameter 'scheduleId' when calling botsBotIdDeploymentsDeploymentIdSchedulesScheduleIdGet");
      }


      var pathParams = {
        'botId': botId,
        'deploymentId': deploymentId,
        'scheduleId': scheduleId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Schedule;

      return this.apiClient.callApi(
        '/bots/{botId}/deployments/{deploymentId}/schedules/{scheduleId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
