/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Zaun);
  }
}(this, function(expect, Zaun) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Zaun.Flow();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Flow', function() {
    it('should create an instance of Flow', function() {
      // uncomment below and update the code to test Flow
      //var instane = new Zaun.Flow();
      //expect(instance).to.be.a(Zaun.Flow);
    });

    it('should have the property fallback (base name: "fallback")', function() {
      // uncomment below and update the code to test the property fallback
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

    it('should have the property priority (base name: "priority")', function() {
      // uncomment below and update the code to test the property priority
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

    it('should have the property expire (base name: "expire")', function() {
      // uncomment below and update the code to test the property expire
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

    it('should have the property _volatile (base name: "volatile")', function() {
      // uncomment below and update the code to test the property _volatile
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

    it('should have the property intents (base name: "intents")', function() {
      // uncomment below and update the code to test the property intents
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

    it('should have the property states (base name: "states")', function() {
      // uncomment below and update the code to test the property states
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

    it('should have the property stateMapper (base name: "stateMapper")', function() {
      // uncomment below and update the code to test the property stateMapper
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

    it('should have the property stateActions (base name: "stateActions")', function() {
      // uncomment below and update the code to test the property stateActions
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

    it('should have the property actions (base name: "actions")', function() {
      // uncomment below and update the code to test the property actions
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

    it('should have the property methods (base name: "methods")', function() {
      // uncomment below and update the code to test the property methods
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

    it('should have the property nlus (base name: "nlus")', function() {
      // uncomment below and update the code to test the property nlus
      //var instane = new Zaun.Flow();
      //expect(instance).to.be();
    });

  });

}));
