/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Zaun);
  }
}(this, function(expect, Zaun) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Zaun.State();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('State', function() {
    it('should create an instance of State', function() {
      // uncomment below and update the code to test State
      //var instane = new Zaun.State();
      //expect(instance).to.be.a(Zaun.State);
    });

    it('should have the property initial (base name: "initial")', function() {
      // uncomment below and update the code to test the property initial
      //var instane = new Zaun.State();
      //expect(instance).to.be();
    });

    it('should have the property _float (base name: "float")', function() {
      // uncomment below and update the code to test the property _float
      //var instane = new Zaun.State();
      //expect(instance).to.be();
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instane = new Zaun.State();
      //expect(instance).to.be();
    });

    it('should have the property enter (base name: "enter")', function() {
      // uncomment below and update the code to test the property enter
      //var instane = new Zaun.State();
      //expect(instance).to.be();
    });

    it('should have the property transit (base name: "transit")', function() {
      // uncomment below and update the code to test the property transit
      //var instane = new Zaun.State();
      //expect(instance).to.be();
    });

    it('should have the property exit (base name: "exit")', function() {
      // uncomment below and update the code to test the property exit
      //var instane = new Zaun.State();
      //expect(instance).to.be();
    });

    it('should have the property end (base name: "end")', function() {
      // uncomment below and update the code to test the property end
      //var instane = new Zaun.State();
      //expect(instance).to.be();
    });

    it('should have the property transitions (base name: "transitions")', function() {
      // uncomment below and update the code to test the property transitions
      //var instane = new Zaun.State();
      //expect(instance).to.be();
    });

  });

}));
