/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/StateAction'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./StateAction'));
  } else {
    // Browser globals (root is window)
    if (!root.Zaun) {
      root.Zaun = {};
    }
    root.Zaun.FlowStateActions = factory(root.Zaun.ApiClient, root.Zaun.StateAction);
  }
}(this, function(ApiClient, StateAction) {
  'use strict';




  /**
   * The FlowStateActions model module.
   * @module model/FlowStateActions
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FlowStateActions</code>.
   * @alias module:model/FlowStateActions
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>FlowStateActions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlowStateActions} obj Optional instance to populate.
   * @return {module:model/FlowStateActions} The populated <code>FlowStateActions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = StateAction.constructFromObject(data['name']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/StateAction} name
   */
  exports.prototype['name'] = undefined;



  return exports;
}));


