/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlowActions', 'model/FlowIntents', 'model/FlowMethods', 'model/FlowNlus', 'model/FlowStateActions', 'model/FlowStates'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FlowActions'), require('./FlowIntents'), require('./FlowMethods'), require('./FlowNlus'), require('./FlowStateActions'), require('./FlowStates'));
  } else {
    // Browser globals (root is window)
    if (!root.Zaun) {
      root.Zaun = {};
    }
    root.Zaun.Flow = factory(root.Zaun.ApiClient, root.Zaun.FlowActions, root.Zaun.FlowIntents, root.Zaun.FlowMethods, root.Zaun.FlowNlus, root.Zaun.FlowStateActions, root.Zaun.FlowStates);
  }
}(this, function(ApiClient, FlowActions, FlowIntents, FlowMethods, FlowNlus, FlowStateActions, FlowStates) {
  'use strict';




  /**
   * The Flow model module.
   * @module model/Flow
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Flow</code>.
   * @alias module:model/Flow
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>Flow</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Flow} obj Optional instance to populate.
   * @return {module:model/Flow} The populated <code>Flow</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fallback')) {
        obj['fallback'] = ApiClient.convertToType(data['fallback'], 'Boolean');
      }
      if (data.hasOwnProperty('priority')) {
        obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
      }
      if (data.hasOwnProperty('expire')) {
        obj['expire'] = ApiClient.convertToType(data['expire'], 'Number');
      }
      if (data.hasOwnProperty('volatile')) {
        obj['volatile'] = ApiClient.convertToType(data['volatile'], 'Boolean');
      }
      if (data.hasOwnProperty('intents')) {
        obj['intents'] = FlowIntents.constructFromObject(data['intents']);
      }
      if (data.hasOwnProperty('states')) {
        obj['states'] = FlowStates.constructFromObject(data['states']);
      }
      if (data.hasOwnProperty('stateMapper')) {
        obj['stateMapper'] = ApiClient.convertToType(data['stateMapper'], 'String');
      }
      if (data.hasOwnProperty('stateActions')) {
        obj['stateActions'] = FlowStateActions.constructFromObject(data['stateActions']);
      }
      if (data.hasOwnProperty('actions')) {
        obj['actions'] = FlowActions.constructFromObject(data['actions']);
      }
      if (data.hasOwnProperty('methods')) {
        obj['methods'] = FlowMethods.constructFromObject(data['methods']);
      }
      if (data.hasOwnProperty('nlus')) {
        obj['nlus'] = FlowNlus.constructFromObject(data['nlus']);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} fallback
   */
  exports.prototype['fallback'] = undefined;
  /**
   * @member {Number} priority
   */
  exports.prototype['priority'] = undefined;
  /**
   * @member {Number} expire
   */
  exports.prototype['expire'] = undefined;
  /**
   * @member {Boolean} volatile
   */
  exports.prototype['volatile'] = undefined;
  /**
   * @member {module:model/FlowIntents} intents
   */
  exports.prototype['intents'] = undefined;
  /**
   * @member {module:model/FlowStates} states
   */
  exports.prototype['states'] = undefined;
  /**
   * @member {String} stateMapper
   */
  exports.prototype['stateMapper'] = undefined;
  /**
   * @member {module:model/FlowStateActions} stateActions
   */
  exports.prototype['stateActions'] = undefined;
  /**
   * @member {module:model/FlowActions} actions
   */
  exports.prototype['actions'] = undefined;
  /**
   * @member {module:model/FlowMethods} methods
   */
  exports.prototype['methods'] = undefined;
  /**
   * @member {module:model/FlowNlus} nlus
   */
  exports.prototype['nlus'] = undefined;



  return exports;
}));


