/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Message'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Message'));
  } else {
    // Browser globals (root is window)
    if (!root.Zaun) {
      root.Zaun = {};
    }
    root.Zaun.ProcessedMessage = factory(root.Zaun.ApiClient, root.Zaun.Message);
  }
}(this, function(ApiClient, Message) {
  'use strict';




  /**
   * The ProcessedMessage model module.
   * @module model/ProcessedMessage
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ProcessedMessage</code>.
   * @alias module:model/ProcessedMessage
   * @class
   * @extends module:model/Message
   */
  var exports = function() {
    var _this = this;
    Message.call(_this);


  };

  /**
   * Constructs a <code>ProcessedMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProcessedMessage} obj Optional instance to populate.
   * @return {module:model/ProcessedMessage} The populated <code>ProcessedMessage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      Message.constructFromObject(data, obj);
      if (data.hasOwnProperty('intent')) {
        obj['intent'] = ApiClient.convertToType(data['intent'], 'String');
      }
      if (data.hasOwnProperty('attributes')) {
        obj['attributes'] = ApiClient.convertToType(data['attributes'], Object);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(Message.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {String} intent
   */
  exports.prototype['intent'] = undefined;
  /**
   * @member {Object} attributes
   */
  exports.prototype['attributes'] = undefined;



  return exports;
}));


