/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Message'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Message'));
  } else {
    // Browser globals (root is window)
    if (!root.Zaun) {
      root.Zaun = {};
    }
    root.Zaun.Schedule = factory(root.Zaun.ApiClient, root.Zaun.Message);
  }
}(this, function(ApiClient, Message) {
  'use strict';




  /**
   * The Schedule model module.
   * @module model/Schedule
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Schedule</code>.
   * @alias module:model/Schedule
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>Schedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Schedule} obj Optional instance to populate.
   * @return {module:model/Schedule} The populated <code>Schedule</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = Message.constructFromObject(data['message']);
      }
      if (data.hasOwnProperty('start')) {
        obj['start'] = ApiClient.convertToType(data['start'], 'String');
      }
      if (data.hasOwnProperty('end')) {
        obj['end'] = ApiClient.convertToType(data['end'], 'String');
      }
      if (data.hasOwnProperty('freqType')) {
        obj['freqType'] = ApiClient.convertToType(data['freqType'], 'String');
      }
      if (data.hasOwnProperty('freqInterval')) {
        obj['freqInterval'] = ApiClient.convertToType(data['freqInterval'], 'Number');
      }
      if (data.hasOwnProperty('users')) {
        obj['users'] = ApiClient.convertToType(data['users'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/Message} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {String} start
   */
  exports.prototype['start'] = undefined;
  /**
   * @member {String} end
   */
  exports.prototype['end'] = undefined;
  /**
   * @member {String} freqType
   */
  exports.prototype['freqType'] = undefined;
  /**
   * @member {Number} freqInterval
   */
  exports.prototype['freqInterval'] = undefined;
  /**
   * @member {Array.<String>} users
   */
  exports.prototype['users'] = undefined;



  return exports;
}));


