/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/StateAction', 'model/StateTransition', 'model/StateTransitions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./StateAction'), require('./StateTransition'), require('./StateTransitions'));
  } else {
    // Browser globals (root is window)
    if (!root.Zaun) {
      root.Zaun = {};
    }
    root.Zaun.State = factory(root.Zaun.ApiClient, root.Zaun.StateAction, root.Zaun.StateTransition, root.Zaun.StateTransitions);
  }
}(this, function(ApiClient, StateAction, StateTransition, StateTransitions) {
  'use strict';




  /**
   * The State model module.
   * @module model/State
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>State</code>.
   * @alias module:model/State
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>State</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/State} obj Optional instance to populate.
   * @return {module:model/State} The populated <code>State</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('initial')) {
        obj['initial'] = ApiClient.convertToType(data['initial'], 'Boolean');
      }
      if (data.hasOwnProperty('float')) {
        obj['float'] = StateTransition.constructFromObject(data['float']);
      }
      if (data.hasOwnProperty('action')) {
        obj['action'] = StateAction.constructFromObject(data['action']);
      }
      if (data.hasOwnProperty('enter')) {
        obj['enter'] = ApiClient.convertToType(data['enter'], 'String');
      }
      if (data.hasOwnProperty('transit')) {
        obj['transit'] = ApiClient.convertToType(data['transit'], 'String');
      }
      if (data.hasOwnProperty('exit')) {
        obj['exit'] = ApiClient.convertToType(data['exit'], 'String');
      }
      if (data.hasOwnProperty('end')) {
        obj['end'] = ApiClient.convertToType(data['end'], 'Boolean');
      }
      if (data.hasOwnProperty('transitions')) {
        obj['transitions'] = StateTransitions.constructFromObject(data['transitions']);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} initial
   */
  exports.prototype['initial'] = undefined;
  /**
   * @member {module:model/StateTransition} float
   */
  exports.prototype['float'] = undefined;
  /**
   * @member {module:model/StateAction} action
   */
  exports.prototype['action'] = undefined;
  /**
   * @member {String} enter
   */
  exports.prototype['enter'] = undefined;
  /**
   * @member {String} transit
   */
  exports.prototype['transit'] = undefined;
  /**
   * @member {String} exit
   */
  exports.prototype['exit'] = undefined;
  /**
   * @member {Boolean} end
   */
  exports.prototype['end'] = undefined;
  /**
   * @member {module:model/StateTransitions} transitions
   */
  exports.prototype['transitions'] = undefined;



  return exports;
}));


