/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Zaun);
  }
}(this, function(expect, Zaun) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Zaun.BotApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BotApi', function() {
    describe('botsBotIdConversePost', function() {
      it('should call botsBotIdConversePost successfully', function(done) {
        //uncomment below and update the code to test botsBotIdConversePost
        //instance.botsBotIdConversePost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsBotIdDelete', function() {
      it('should call botsBotIdDelete successfully', function(done) {
        //uncomment below and update the code to test botsBotIdDelete
        //instance.botsBotIdDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsBotIdExecObjectPost', function() {
      it('should call botsBotIdExecObjectPost successfully', function(done) {
        //uncomment below and update the code to test botsBotIdExecObjectPost
        //instance.botsBotIdExecObjectPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsBotIdGet', function() {
      it('should call botsBotIdGet successfully', function(done) {
        //uncomment below and update the code to test botsBotIdGet
        //instance.botsBotIdGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsBotIdPut', function() {
      it('should call botsBotIdPut successfully', function(done) {
        //uncomment below and update the code to test botsBotIdPut
        //instance.botsBotIdPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsBotIdVersionsGet', function() {
      it('should call botsBotIdVersionsGet successfully', function(done) {
        //uncomment below and update the code to test botsBotIdVersionsGet
        //instance.botsBotIdVersionsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsGet', function() {
      it('should call botsGet successfully', function(done) {
        //uncomment below and update the code to test botsGet
        //instance.botsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsPost', function() {
      it('should call botsPost successfully', function(done) {
        //uncomment below and update the code to test botsPost
        //instance.botsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
