/**
 * Zaun
 * Zaun service 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Zaun);
  }
}(this, function(expect, Zaun) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Zaun.DeploymentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeploymentApi', function() {
    describe('botsBotIdDeploymentsDepIdDelete', function() {
      it('should call botsBotIdDeploymentsDepIdDelete successfully', function(done) {
        //uncomment below and update the code to test botsBotIdDeploymentsDepIdDelete
        //instance.botsBotIdDeploymentsDepIdDelete(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsBotIdDeploymentsDepIdGet', function() {
      it('should call botsBotIdDeploymentsDepIdGet successfully', function(done) {
        //uncomment below and update the code to test botsBotIdDeploymentsDepIdGet
        //instance.botsBotIdDeploymentsDepIdGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsBotIdDeploymentsDepIdPut', function() {
      it('should call botsBotIdDeploymentsDepIdPut successfully', function(done) {
        //uncomment below and update the code to test botsBotIdDeploymentsDepIdPut
        //instance.botsBotIdDeploymentsDepIdPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsBotIdDeploymentsGet', function() {
      it('should call botsBotIdDeploymentsGet successfully', function(done) {
        //uncomment below and update the code to test botsBotIdDeploymentsGet
        //instance.botsBotIdDeploymentsGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('botsBotIdDeploymentsPost', function() {
      it('should call botsBotIdDeploymentsPost successfully', function(done) {
        //uncomment below and update the code to test botsBotIdDeploymentsPost
        //instance.botsBotIdDeploymentsPost(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
